### ISSUE TITLE
Make Bitcoin RPC easier

### ISSUE THREAD

**Issue by justinmoon** [vulpemventures/nigiri#82] opened 2020-08-08 02:24 UTC
This is what I'm doing now:

```
docker exec -it bitcoin /bin/bash
bitcoin-cli -datadir=/config/ getblockchaininfo
```

Would be nice if that was easier. It also took me 30 minutes to figure that out.

**Comment by tiero** [comment] 2020-08-09 10:39
Hello @justinmoon thanks for reaching out.

This feedback is very important, which means the documentation must be improved.

To use the node RPC you could either enter in the container and use the CLI as you correctly did or either you could use the command-line on your host system if you have it.

Another solution popped up in the past (but never implemented) could be to print in the console after `nigiri start` an alias, so the user is free to either add to the current terminal session or to the bash profile if any.

Somtheing like:

```
$ alias bcli='docker exec -it resources_bitcoin_1 bitcoin-cli -datadir=config'
$ bcli getblockchaininfo
```

PS: We could also add it automatically to the bash profile at installation time, but it seems too aggressive. What do you think?

**Comment by justinmoon** [comment] 2020-08-20 18:57
Adding to .bashrc is too aggressive IMO.

Adding to README should be sufficient or `nigigi start` output would both help.

Or maybe adding a `nigiri rpc` command?

**Comment by tiero** [comment] 2020-08-24 11:32
In the beginning, we didn't want to wrap other RPC/REST services in the nigiri CLI, mostly because would have been a bit challenging to maintain any future additions of services (We wanted to add Lighting boxes too, but then [Polar](https://github.com/jamaljsr/polar) came out and we decided to pivot to focus only on bitcoin and liquid and release CI plugin useful for developers like https://github.com/vulpemventures/nigiri-travis) 

That being said, I think now could makes sense to wrap bitcoin and elements CLIs under a nigiri subcommand and to add the custom services injected by [chopsticks](https://github.com/vulpemventures/nigiri-chopsticks) like the `faucet` or the Liquid `mint`

How this looks like to you? @justinmoon 

```sh
$ nigiri rpc <bitcoin-cli command>
$ nigiri rpc --liquid <elements-cli command>
$ nigiri faucet <bitcoin address>
$ nigiri faucet --liquid <elements address>
$ nigiri mint <elements address>
$ nigiri broadcast <hex>
$ nigiri broadcast --liquid <hex>
```

**Comment by justinmoon** [comment] 2020-08-26 01:50
I'm not sure if that would be helpful. It could be, but I'm not sure. Just mentioning is what was really needed.

**Comment by notmandatory** [comment] 2020-08-26 17:39
I've been using the `docker exec` method but I think your proposed `nigiri rpc` and `nigiri faucet` commands would be a nice short cuts. I'm happy to test it out when you have a PR ready.

**Comment by tiero** [comment] 2020-09-14 14:09
Hey @notmandatory and all whom interested

Try [out latest master ](https://github.com/vulpemventures/nigiri/commit/bb08c84ae13ad8c7bb8d5f2c7bbefa5f19465a5c) if you can and tells what do you think.


```
# clone-pull and checkout to that commit
$ bash scripts/clean
$ bash scripts/install

# on linux
$ bash scripts/build linux amd64
# on macos
$ bash scripts/build darwin amd64
# Run 
$  ./build/nigiri-<OS>-amd64 start 
$ ./build/nigiri-<OS>-amd64 rpc getnewaddress
```

**Comment by notmandatory** [comment] 2020-09-16 04:35
I can confirm the `rpc` command does what I was looking for, I think printing out all the ports is also a nice touch:

```
➜  nigiri git:(master) ./build/nigiri-darwin-amd64 start
Creating bitcoin ... done
Creating electrs ... done
Creating chopsticks ... done
Creating esplora    ... done
Bitcoin services:
   esplora:       localhost:5000
   electrs:       localhost:3002
   electrs_rpc:   localhost:51401
   chopsticks:    localhost:3000
   peer:          localhost:18432
   node:          localhost:18433
➜  nigiri git:(master) ./build/nigiri-darwin-amd64 rpc getnewaddress
2NERe6hyryewQ92HCwtNCyg6ZWSBS35GNRq
➜  nigiri git:(master) ./build/nigiri-darwin-amd64 rpc getbalance      
50.00000000
➜  nigiri git:(master) ./build/nigiri-darwin-amd64 rpc generatetoaddress 1 "2NERe6hyryewQ92HCwtNCyg6ZWSBS35GNRq"
[
  "4b19fb402f0f49bb7595cf0b5fd2ad18ceda49e10ca09681f25bf108803098d7"
]
➜  nigiri git:(master) ./build/nigiri-darwin-amd64 rpc getbalance                                               
100.00000000
```

**Comment by notmandatory** [comment] 2020-09-16 05:04
I also tried the `faucet` command which looks good too. It seems to be a shortcut for mining a block and sending 1 BTC with a tx fee to the destination address. This seems like a common use case.

```
➜  nigiri git:(master) ./build/nigiri-darwin-amd64 faucet "2NERe6hyryewQ92HCwtNCyg6ZWSBS35GNRq"
txId: e010c1c39c8cd0568fd148f5bf67a660b3013e8dbd95bbc87222abc447e49834
➜  nigiri git:(master) ./build/nigiri-darwin-amd64 faucet "2NERe6hyryewQ92HCwtNCyg6ZWSBS35GNRq"
txId: 64f7669ac6bba86a5ae75a8b3ec8c550b60b47d3591e98e19b77ed8ab085cbb0
➜  nigiri git:(master) ./build/nigiri-darwin-amd64 rpc getbalance                              
199.99993360
```

**Comment by tiero** [comment] 2020-09-16 08:36
Cool! Thanks for taking the time to test it.

the faucet command is just wrapping the  `/faucet` endpoint on port :3000 (added by  the `nigiri-chopsticks` to the electrs REST interface), that sends to an address and generate a block one shot.

We are working on adding the `push` command that calls the `/tx` endpoint. This is exactly the same endpoint of electrs (ie. not added by us), but we just intercept that to automatically generate a block as well.

Closing this issue for now. The README will be updated when we tag a new release.

**Closed by tiero** 2020-09-16 08:36 UTC
