### ISSUE TITLE
`nigiri logs --help` could be improved

### ISSUE THREAD

**Issue by justinmoon** [vulpemventures/nigiri#83] opened 2020-08-26 01:58 UTC
```
Check service logs

Usage:
  nigiri logs [flags]

Flags:
  -h, --help     help for logs
      --liquid   Set to see logs of a liquid service

Global Flags:
      --datadir string   Set nigiri default directory (default "/home/justin/.nigiri")
```

It's unclear what "flags" should be. The README explains it, but this help command should too.

**Comment by tiero** [comment] 2020-09-02 10:27
That's true, Thanks. 

This is a duplicate of https://github.com/vulpemventures/nigiri/issues/75#issuecomment-663063982

**Closed by tiero** 2020-09-02 10:27 UTC

**Comment by tiero** [comment] 2020-09-11 00:42
Fixed. You can install the latest prebuilt binary or build it from the source. Now it lists the available services to be passed to the logs command
