### ISSUE TITLE
Config file permissions prevent container from building

### ISSUE THREAD

**Issue by thunderbiscuit** [vulpemventures/nigiri#81] opened 2020-07-29 16:54 UTC
Hey guys,

I'm testing Nigiri on my Ubuntu setup and running into a small problem. I think the container needs to read the config file in my `~/.nigiri/` directory but it doesn't have permission to do so by default, so it never quite builds the container. Is there a "proper" fix to that or is it just about changing the folder permissions? It's not mentioned in the readme so I wonder if it's not a normal problem and if it has to do with my docker setup or something else.

Working fine on my Mac, but Linux docker is quite different. Wondering if there is a simple fix I don't know about...

**Comment by tiero** [comment] 2020-07-29 17:30
Weird. It should give the right permission at install time. Let me see.

How do you installed nigiri? Via bash one liner (ie. pre-built binary) or you built from source yourself? @thunderbiscuit

**Comment by thunderbiscuit** [comment] 2020-07-29 17:39
Built from source. But to be honest I've been messing with my Ubuntu setup, created a new user, uninstalled/reinstalled Docker, etc... I have a feeling the problem is coming from me.

**Comment by tiero** [comment] 2020-07-29 17:45
This is the [bash installer script ](https://github.com/vulpemventures/nigiri-installer-script/blob/master/index.sh) that pulls latest binaries, meanwhile, this script is [used in the from source steps ](https://github.com/vulpemventures/nigiri/blob/master/scripts/install)

I use Linux as the main machine, and it always worked with the given permissions. Maybe you some strict policies in your home directory, but this seems weird. Is it your docker into the sudoers group?

**Comment by tiero** [comment] 2020-07-29 17:48
> Here is the error in the logs, repeated over and over:
> 
> ```
> sudo nigiri logs node
> 
> bitcoin_1     | EXCEPTION: N5boost10filesystem16filesystem_errorE       
> bitcoin_1     | boost::filesystem::create_directory: Permission denied: "/config/regtest"       
> bitcoin_1     | bitcoin in AppInit() 
> ```

yes it seems that the mounted directory (in `~/.nigiri` folder) has stricter permissions.

**Comment by thunderbiscuit** [comment] 2020-07-29 17:51
I'm not sure how to check for the groups `docker` belongs to. I tried `groups docker` but it tells me that there is no user named `docker`.

**Comment by tiero** [comment] 2020-07-29 17:52
Have you run this before `sudo usermod -aG docker $USER` ?

**Comment by thunderbiscuit** [comment] 2020-07-29 17:53
No I have not. I saw it was supposedly not the safest way to go about things... didn't want to try it. Should I?

**Comment by tiero** [comment] 2020-07-29 17:58
> No I have not. I saw it was supposedly not the safest way to go about things... didn't want to try it. Should I?

I mean it's just a matter of using docker with or without sudo everytime. But should not be this the reason why it hasn't the righ permissions in the datadir folder. I'll try to reproduce myself first.

**Comment by thunderbiscuit** [comment] 2020-07-29 17:59
Yeah don't sweat it. the bitcoin-regtest-box is now also giving me grief. Not finding the apline tar file... I really think it's my docker setup that I might need to look at.

**Comment by thunderbiscuit** [comment] 2020-07-29 18:21
Ok now it's getting weird. I started from scratch with Docker Engine, and Docker Compose, deleted all Nigiri stuff... recloned the repo. Fresh start.

Once I build, I get in the build directory, and try to run the executable right from there, and it's throwing an error saying `Error: open /home/username/.nigiri/nigiri.config.json: no such file or directory`. 

The plot thickens...

**Comment by thunderbiscuit** [comment] 2020-07-29 20:29
A few more clues to this puzzle:

1. If I install the binaries using the 1-liner with curl, it installs the binary in `~/bin/`, and adds the that path to my `user`, but not to `sudo`. And because docker (with default settings) requires sudo to run, when I then use `sudo nigiri start`, it can't find nigiri. I had to manually fix the sudo path using `sudo visudo`.
2. Once I got that fixed, we're back to the same error I get when I compile from source: it can't find the `nigiri.config.json` file and so aborts. The file indeed is not there at all under `~/.nigiri/`. Is it supposed to be created within the build script? I can't find the line where that happens.

@tiero Sorry to be a pain man. I feel like it worked so well on my Mac! Don't know why I'm having a hard time with my Linux setup. Let me know if this is better handled in chat format instead of polluting your repo with a bunch of back and forth. We're a bunch of people interested in using nigiri on the bitcoindevkit slack, you should join if you're interested!

**Comment by tiero** [comment] 2020-09-01 11:18
This seems to be fixed by https://github.com/vulpemventures/nigiri-installer-script/pull/7. Closing

**Closed by tiero** 2020-09-01 11:18 UTC
